import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
    <Head>
      <title>lobo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <h1 className="text-3xl font-bold">Welcome to Lobo 🐺</h1>
    <Link href="/new-game">
      <a className="bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded">
        New Game
      </a>
    </Link>
    <Link href="/join">
      <a className="bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded">
        Join Game
      </a>
    </Link>
    <Link href="/all-cards">
      <a className="bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded">
        All cards
      </a>
    </Link>
  </div>
  )
}

export default Home
